_DEBUG = False
import os,argparse,time,shutil
from datetime import datetime
from script import service_automation 
from log_email import log_email

parser = argparse.ArgumentParser()
parser.add_argument("-i" ,"--input", type = str, help="input path")
parser.add_argument("-o" ,"--output", type = str, help="output path")
parser.add_argument("-p" ,"--processed", type = str, help="processed directory path")

args=parser.parse_args()
argv1 = args.input
argv2 = args.output
argv3 = args.processed

wrapper_log_file_path = os.path.join(argv1,"wrapper.log")
wrapper_file = open(wrapper_log_file_path, 'w')
start_time = datetime.now()
wrapper_file.write('Wrapper started at {}'.format(start_time)+"\n")

def generate_email(s_l):
    from_email = "genoapth4@supratechs.net"
    to_email = "devendra.parihar@supratechlabs.com,"
    password = "NeubergGenetics$321"
    subject = "HLA CSV generation - autogenerated"
    body = f"""Files generated for this samples {s_l[0]}
Files not generated for this samples {s_l[-1]}
    """
    log_email(from_email, to_email, password, subject, body)

while True:
    time.sleep(15)
    excel=""
    csv=""
    try:
        excel_file = [x for x in os.listdir(argv1) if x.endswith(".xlsx")]
        excel = excel_file[0]
        csv_file = [x for x in os.listdir(argv1) if x.endswith(".csv")]
        csv = csv_file[0]
    except IndexError:
        pass
    
    if excel!="" and csv!="":
        s_l = service_automation(excel, csv, argv1, argv2).process()
        wrapper_log_file_path = os.path.join(argv1,"wrapper.log")
        wrapper_file = open(wrapper_log_file_path, 'a')
        now_time = datetime.now()
        wrapper_file.write('At {}'.format(now_time)+" two files provided "+excel+" and "+csv+"\n")
        ps=str(now_time).split()[0]
        os.rename(os.path.join(argv1,csv),os.path.join(argv1,ps+"_"+csv))
        os.rename(os.path.join(argv1,excel),os.path.join(argv1,ps+"_"+excel))
        try:
            shutil.move(os.path.join(argv1,ps+"_"+excel),argv3)
            shutil.move(os.path.join(argv1,ps+"_"+csv),argv3)
        except shutil.Error:
            os.remove(os.path.join(argv1,ps+"_"+csv))
            os.remove(os.path.join(argv1,ps+"_"+excel))
        
        generate_email(s_l)

    else:
        wrapper_log_file_path = os.path.join(argv1,"wrapper.log")
        wrapper_file = open(wrapper_log_file_path, 'a')
        now_time = datetime.now()
        wrapper_file.write('At {}'.format(now_time)+" no files provided\n")
